<a href="https://colab.research.google.com/github/manishtomarr1/Machine-Learning/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataSet = pd.read_csv('Data.csv')
x = dataSet.iloc[:, :-1].values
y = dataSet.iloc[:, -1].values
# first row then colomn is iloc function, here we take only last colomn and whole row of last colomn
# iloc take the index of the colomn and rows, : means we take all the rows, :-1 means take every colomn accept last colomn.
# x is feature (independent)
#.value means we take all the values
# y is the dependent variable vector

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
print(dataSet)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


## Taking care of missing data

In [ ]:
#in this shell we will deal with the missing data -> taking average of the whole colomn
#scilet-learn is lib of DS including lot of data preprocessing tools

from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values = np.nan, strategy = 'mean') # this is how we make the object of any class in the python , imputer is the object
imputer.fit(x[:, 1:3]) #take three because last value is exclude now it will take all rows from colomn 1 to 2 we ignore colomn 0 because it containing strings
x[:, 1:3] = imputer.transform(x[:, 1:3]) #now we are updating the features with updated values

#sklearn is Lib and SimpleImputer is the class in that Lib
# fit will automatically find the missing value and find the mean
# transform replace the missing values to mean, firt use fit then transform according to fit

In [ ]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers= [('encoder',OneHotEncoder(), [0] )], remainder='passthrough')
x = np.array(ct.fit_transform(x))

#use np.array because later train method want the the numpy array to train modle

#transformers -> args - 1- type of transformation, 2- name of transformation, 3- apply on which

In [ ]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#LabelEncoder used to convert in 0 & 1's

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)


[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)


[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
#feature scaling is find the relation in data or the connectivity in data by mean and standard dev.
#apply after splitting because if we do first then it will take mean of whole data we can not want to apply this to whole data because it will new data with new observation, prevent information leckage.
#we use this for domination like the irrelative data is dominated by found the scaling value.
# strandardisation = x-mean(x)/sd(x) -> perfect in every case , values b/w [-3,3]
# normalisation = x-min(x)/(max(x)-min(x)) -> used in some specefic case.
#improve optimasation

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:]) #all rows from colomn 3 to last -> see train data
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

#fit get mean, sd and transform put in formula and calculate here fit_trans do both in same
#test me transform lagaya bs kyuki we only want the value of test data we dont want to change existing scaler value


In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(x_test)


[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
